import {createScene} from './scene.js';
const $=s=>document.querySelector(s),fmt=(v,n=2)=>v===null||v===undefined?'—':Number(v).toFixed(n),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let catalog,run=null,missions={},progress=0,playing=false,last=0,lastFetch=0,busy=false,engine='A',results=null,revealed=null,validation=null,generation=0;
const scene=createScene($('#scene'));
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw Error(value.error||'Request failed');return value}
function error(e){$('#error').textContent=e.message;$('#error').hidden=false;playing=false;$('#play').textContent='▶'}
const activeLot=()=>catalog.lots.find(l=>l.lot_id===$('#lotA').value);
function fillLots(which){const id=$('#api'+which).value;$('#lot'+which).innerHTML=catalog.lots.filter(l=>l.api===id).map(l=>`<option value="${l.lot_id}">${l.mission} · ${l.lot_id} · ${l.days_in_space}d</option>`).join('')}
function updateSelection(){playing=false;generation++;run=null;results=null;revealed=null;progress=0;$('#play').disabled=true;$('#restart').disabled=true;$('#scrub').disabled=true;$('#scrub').value=0;$('#blind-status').textContent='HIDDEN';$('#second').hidden=$('#mode').value!=='LTDO';$('#split').textContent=$('#mode').value==='LTDO'?'6 training APIs / 2 held out · all lots excluded':'7 training APIs / 1 held out · all lots excluded';showProfile();renderResults();renderCoverage();$('#phase').textContent='READY TO REPLAY';$('#progress-label').textContent='0.0%';$('#charts').innerHTML='';$('#live-values').innerHTML='<p class="quiet">Prepare replay to load observed environmental streams.</p>';scene.update(0,null,200)}
function showProfile(){const l=activeLot();$('#profile').innerHTML=`<span class="eyebrow">ONBOARD SAMPLE</span><h3>${esc(l.api)}</h3><div class="formula">${esc(l.molecular_formula)}</div><p class="quiet">${esc(l.formulation)} · ${esc(l.dosage)}<br>${esc(l.packaging)}</p><div class="descriptor-grid">${[['tpsa','TPSA · Å²','Polar molecular surface area'],['xlogp','XLogP','Lipophilicity / water-vs-fat preference'],['molecular_weight','MW · g/mol','Molecular weight'],['hba','HBA','Hydrogen bond acceptors'],['hbd','HBD','Hydrogen bond donors'],['rotatable_bonds','Rotatable bonds','Molecular flexibility'],['complexity','Complexity','Molecular structural complexity']].map(([key,label,tip])=>`<div title="${tip}"><small>${label}</small>${l[key]}</div>`).join('')}</div><p class="quiet">Descriptor profile. A verified molecular structure is not available in this archive.</p>`;$('#boundary-note').textContent=l.timeline_note+'. Milestone labels show sequence; the actual timeline is not evenly spaced.'}
const vars=[['radiation_combined','Radiation dose rate','µGy/h'],['temperature','Temperature','°C'],['relative_humidity','Relative humidity','%RH'],['co2','CO₂','ppm'],['pressure','Pressure','kPa'],['oxygen','Oxygen','%']];
function renderCoverage(){const l=activeLot();$('#coverage').innerHTML=vars.map(([key,title])=>{const value=l.coverage[key+'_coverage_pct'];return `<div class="coverage-row"><div><span>${title}</span><span>${fmt(value,1)}%</span></div><meter min="0" max="100" value="${value}" aria-label="${title} coverage">${fmt(value,1)}%</meter></div>`}).join('')}
function live(data){const l=activeLot(),s=data.samples[l.lot_id];$('#utc').textContent=new Date(s.timestamp*1000).toISOString().replace('T',' ').slice(0,19)+' UTC';$('#phase').textContent=s.mission_phase;
 const rad=s.radiation_combined.value,p95=missions[l.mission].radiation_p95_uGy_h;
 $('#elevated').hidden=rad===null||rad<p95;$('#elevated').textContent=`ELEVATED RADIATION · ${fmt(rad)} µGy/h ≥ P95 ${fmt(p95)}`;
 $('#live-values').innerHTML=vars.map(([key,title,unit])=>{const v=s[key];return `<div class="reading ${v.value===null?'unavailable':''}"><span>${title}</span><strong>${v.value===null?'NO DATA':fmt(v.value,key==='co2'?0:2)+' '+unit}</strong><small>${v.status.replaceAll('_',' ')} · ${key==='pressure'||key==='oxygen'?'':'PROXY '+v.spatial_relevance}</small></div>`}).join('')+`<div class="reading"><span>Observed cumulative dose</span><strong>${fmt(s.cumulative_radiation_mGy,3)} mGy</strong><small>DERIVED · GAPS NOT FILLED</small></div><details><summary>Independent dosimeters</summary><p>DosTel1: ${fmt(s.radiation_sensor1.value)} µGy/h<br>DosTel2: ${fmt(s.radiation_sensor2.value)} µGy/h<br>Overlapping sensors are averaged, never summed.</p></details>`;
 if(run.lot_ids.length===2){const id=run.lot_ids[1],other=catalog.lots.find(l=>l.lot_id===id),o=data.samples[id];$('#live-values').innerHTML+=`<div class="reading"><span>${esc(other.api)} / ${other.mission}</span><strong>${fmt(o.cumulative_radiation_mGy,2)} mGy</strong><small>${o.mission_phase} · ${new Date(o.timestamp*1000).toISOString().slice(0,10)}<br>OWN MISSION · SAME NORMALIZED PROGRESS</small></div>`}
 scene.update(progress,rad,p95);if(data.prediction){results=data.prediction;revealed=data.published_result;renderResults()}}
async function prepare(){try{$('#error').hidden=true;playing=false;const g=++generation;const l=activeLot(),held=[$('#apiA').value],ids=[l.lot_id];if($('#mode').value==='LTDO'){held.push($('#apiB').value);ids.push($('#lotB').value)}
 const r=await api('/api/run',{held_out_apis:held,lot_ids:ids});if(g!==generation)return;run=r;progress=0;results=null;revealed=null;$('#scrub').value=0;$('#blind-status').textContent='HIDDEN';
 for(const id of ids){const lot=catalog.lots.find(l=>l.lot_id===id);if(!missions[lot.mission])missions[lot.mission]=await api('/api/mission/'+lot.mission)}
 $('#play').disabled=false;$('#restart').disabled=false;$('#scrub').disabled=false;renderCharts();renderResults();await tickServer();$('#play').focus();}catch(e){error(e)}}
async function tickServer(){if(!run||busy)return;busy=true;const id=run.simulation_id,g=generation,p=progress;try{const data=await api(`/api/run/${id}/advance`,{progress:p});if(g===generation&&id===run?.simulation_id)live(data)}catch(e){error(e)}finally{busy=false}}
function renderCharts(){const l=activeLot(),p=missions[l.mission];if(!p)return;
 const data=[['radiation_combined','Dose rate','µGy/h'],['cumulative','Observed cumulative dose','mGy'],['temperature','Temperature','°C'],['relative_humidity','Relative humidity','%RH'],['co2','CO₂','ppm']];
 $('#charts').innerHTML=data.map(([key,title,unit])=>{
  const raw=key==='cumulative'?p.cumulative_mGy:p.series[key].value;const points=[];
  p.timestamp.forEach((t,i)=>{if(t>=l.times[0]&&t<=l.times[3]){let value=raw[i];if(t<l.times[1]||t>=l.times[2])value=key==='cumulative'?(t<l.times[1]?0:l.replay_dose_mGy):null;points.push([t,value])}});
  const values=points.map(p=>p[1]).filter(v=>v!==null);const min=key==='cumulative'?0:Math.min(...values),max=Math.max(...values);let path='',open=false;
  for(const [t,v] of points){if(v===null){open=false;continue}const x=(t-l.times[0])/(l.times[3]-l.times[0])*300,y=60-(v-min)/(max-min||1)*53;path+=`${open?'L':'M'}${x.toFixed(2)},${y.toFixed(2)} `;open=true}
  return `<div class="chart"><header>${title} <span>${unit}</span></header><svg viewBox="0 0 300 65" preserveAspectRatio="none" role="img" aria-label="Historical ${title} with missing-data gaps"><path d="${path}" fill="none" stroke="${key==='cumulative'?'#cbdca5':'#73b4da'}" stroke-width="1.2"/><line class="chart-cursor" x1="0" x2="0" y1="0" y2="65" stroke="#eee" opacity=".6"/></svg><small>${values.length?fmt(min,1)+' — '+fmt(max,1):'NO HISTORICAL DATA'} · observed support only</small></div>`}).join('');}
function renderResults(){const target=$('#prediction');if(!results){target.innerHTML='<div class="locked"><span>◇</span><h3>Awaiting mission completion</h3><p>Published experiment stays hidden.<br>Complete or scrub to landing to calculate the endpoint.</p></div>';return}
 const selected=results.filter(r=>r.model===engine);target.innerHTML=selected.map(r=>{const actual=revealed?.find(a=>a.lot_id===r.lot_id&&a.model===engine);return `<div class="endpoint"><div class="endpoint-head"><span>${esc(r.test_api)} / ${esc(r.lot_id)}</span><span>${r.validation_type} · ${r.training_api_count} TRAINING APIs</span></div><strong class="big">${fmt(r.predicted_delta_api)}%</strong> <span>predicted ΔAPI</span><p class="interval">95% approximate predictive interval [${fmt(r.uncertainty_lower)}, ${fmt(r.uncertainty_upper)}]%<br>Stability ratio: ${fmt(100+r.predicted_delta_api)}% of matched ground API</p><p class="domain">${r.domain_status.replaceAll('_',' ')} · chemical distance ${fmt(r.domain_distance)}${r.domain_status==='OUT_OF_DOMAIN'?'<br>OUTSIDE TRAINING CHEMICAL DOMAIN — HIGH UNCERTAINTY':''}</p><div class="contributions">${Object.entries(r.contributions).map(([k,v])=>`<span>${esc(k)}<br>${fmt(v)} pp</span>`).join('')}</div>${actual?`<div class="revealed"><div><small>PUBLISHED EXPERIMENT</small>${fmt(actual.actual_delta_api)}%</div><div><small>ABSOLUTE ERROR</small>${fmt(actual.absolute_error)} pp</div></div><p class="quiet">Possible contributors: limited chemical diversity, formulation and postflight storage differences, measurement uncertainty, proxy sensors and telemetry gaps. An error does not identify its cause.</p>`:''}</div>`}).join('')+`<p class="quiet">Intervals: 400 training-API bootstrap refits + inner-held-API residuals. Approximate and uncalibrated; wide or physically impossible bounds flag instability.</p>${revealed?'':`<button id="reveal" class="primary">Reveal published experiment ↗</button>`}`;
 $('#reveal')?.addEventListener('click',async()=>{try{const d=await api(`/api/run/${run.simulation_id}/reveal`,{});revealed=d.published_result;$('#blind-status').textContent='REVEALED';renderResults()}catch(e){error(e)}})}
function updateProgressUI(){const l=activeLot();$('#scrub').value=Math.round(progress*10000);$('#progress-label').textContent=fmt(progress*100,1)+'%';$('#elapsed').textContent='T + '+fmt(progress*(l.times[3]-l.times[0])/86400)+' DAYS';document.querySelectorAll('.chart-cursor').forEach(e=>{e.setAttribute('x1',progress*300);e.setAttribute('x2',progress*300)})}
function animation(time){requestAnimationFrame(animation);const dt=Math.min((time-last)/1000,.2);last=time;if(!playing||!run)return;const l=activeLot(),speed=$('#speed').value;progress=Math.min(1,progress+dt*(speed==='auto'?1/60:Number(speed)/(l.times[3]-l.times[0])));updateProgressUI();if(time-lastFetch>450||progress===1){lastFetch=time;tickServer()}if(progress===1){playing=false;$('#play').textContent='▶';const final=()=>{if(busy)setTimeout(final,50);else tickServer()};final()}}
function showValidation(){if(!validation)return;const type=$('#validation-filter').value,m=$('#engine-filter').value,a=$('#api-filter').value;$('#validation-rows').innerHTML=validation.filter(r=>r.validation_type===type&&r.model===m&&(a==='all'||r.test_api===a)).map(r=>`<tr><td>${esc(r.held_out_pair)}</td><td>${esc(r.test_api)}<br>${r.lot_id}</td><td>${fmt(r.predicted_delta_api)}</td><td>${fmt(r.actual_delta_api)}</td><td>${fmt(r.absolute_error)}</td><td>[${fmt(r.uncertainty_lower)}, ${fmt(r.uncertainty_upper)}]</td><td>${r.domain_status.replaceAll('_',' ')}</td></tr>`).join('')}
async function init(){try{catalog=await api('/api/catalog');for(const id of ['#apiA','#apiB'])$(id).innerHTML=catalog.apis.map(a=>`<option>${a}</option>`).join('');$('#apiA').value='Caffeine';$('#apiB').value='Diazepam';fillLots('A');fillLots('B');updateSelection();$('#api-filter').innerHTML+=[...catalog.apis].map(a=>`<option>${a}</option>`).join('');$('#metrics').innerHTML=catalog.summary.map(r=>`<div class="metric"><h3>${r.validation} / ENGINE ${r.model}</h3><p>R² ${fmt(r.r2,3)}<br>RMSE ${fmt(r.rmse,3)} pp<br>MAE ${fmt(r.mae,3)} pp</p></div>`).join('');requestAnimationFrame(animation)}catch(e){error(e)}}
$('#prepare').onclick=prepare;$('#apiA').onchange=()=>{fillLots('A');if($('#apiB').value===$('#apiA').value){$('#apiB').value=catalog.apis.find(a=>a!==$('#apiA').value);fillLots('B')}updateSelection()};$('#apiB').onchange=()=>{fillLots('B');updateSelection()};for(const s of ['#lotA','#lotB','#mode'])$(s).onchange=updateSelection;
$('#play').onclick=()=>{if(progress===1)return;playing=!playing;$('#play').textContent=playing?'Ⅱ':'▶'};$('#restart').onclick=prepare;
$('#scrub').oninput=()=>{playing=false;$('#play').textContent='▶';progress=Number($('#scrub').value)/10000;results=null;revealed=null;renderResults();updateProgressUI()};$('#scrub').onchange=()=>{const go=()=>{if(busy)setTimeout(go,50);else tickServer()};go()};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('selected',x===b));scene.view(b.dataset.view)});$('#zoom-in').onclick=()=>scene.zoom(-1);$('#zoom-out').onclick=()=>scene.zoom(1);
document.querySelectorAll('[data-engine]').forEach(b=>b.onclick=()=>{engine=b.dataset.engine;document.querySelectorAll('[data-engine]').forEach(x=>x.classList.toggle('selected',x===b));$('#model-factors').innerHTML=engine==='A'?'Used: TPSA + XLogP + molecular weight.<br>Radiation and cabin telemetry are available in replay only.':'Used: TPSA + XLogP + molecular weight + observed station dose.<br>Experimental additive dose term; no validated causal effect.';renderResults()});
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{playing=false;$('#play').textContent='▶';document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===b.dataset.page));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===b))});
$('#load-validation').onclick=async()=>{try{validation=await api('/api/validation');showValidation()}catch(e){error(e)}};for(const s of ['#validation-filter','#engine-filter','#api-filter'])$(s).onchange=showValidation;
$('#new-drug').onsubmit=async e=>{e.preventDefault();try{$('#hyp-result').textContent='Checking training-domain distance and uncertainty…';const body=Object.fromEntries(new FormData(e.target));const r=await api('/api/hypothetical',body);$('#hyp-result').innerHTML=`${r.domain_status==='OUT_OF_DOMAIN'?'<div class="domain-warning">OUTSIDE TRAINING CHEMICAL DOMAIN<br>Prediction uncertainty is high. Do not use for decisions.</div>':''}<div class="hyp-output">${esc(r.api)} · ${r.domain_status.replaceAll('_',' ')}<br>Predicted ΔAPI: ${fmt(r.prediction)}%<br>Approximate 95% predictive interval: [${fmt(r.uncertainty_lower)}, ${fmt(r.uncertainty_upper)}]%<br><small>${r.warning}</small></div>`}catch(e){error(e)}};
init();
